#!/bin/bash

echo "AI Apply Landing Page Setup Instructions"
echo "========================================"
echo ""
echo "To fix npm permissions and run the project:"
echo ""
echo "1. First, fix npm cache permissions:"
echo "   sudo chown -R $(whoami) ~/.npm"
echo ""
echo "2. Clean install dependencies:"
echo "   rm -rf node_modules package-lock.json"
echo "   npm install"
echo ""
echo "3. Install UI dependencies (if needed):"
echo "   npm install class-variance-authority @radix-ui/react-slot clsx tailwind-merge lucide-react"
echo ""
echo "4. Start the development server:"
echo "   npm run dev"
echo ""
echo "The app will be available at http://localhost:3000"
echo ""
echo "Project Structure:"
echo "- Hero component: src/components/ui/hero-with-mockup.tsx"
echo "- Main page: src/app/page.tsx"
echo "- Styles: src/app/globals.css"